/* 1332. Remove Palindromic Subsequences

You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string if it is generated by deleting some characters of a given string without changing its order. Note that a subsequence does not necessarily need to be contiguous.

A string is called palindrome if is one that reads the same backward as well as forward.

 

Example 1:

Input: s = "ababa"
Output: 1
Explanation: s is already a palindrome, so its entirety can be removed in a single step.
Example 2:

Input: s = "abb"
Output: 2
Explanation: "abb" -> "bb" -> "". 
Remove palindromic subsequence "a" then "bb".
Example 3:

Input: s = "baabb"
Output: 2
Explanation: "baabb" -> "b" -> "". 
Remove palindromic subsequence "baab" then "b".


*/

#include <stdio.h>
#include <stdbool.h>
#include <string.h>

bool isPalindrome(char* s) {
    int left = 0;
    int right = strlen(s) - 1;

    while (left < right) {
        if (s[left] != s[right]) {
            return false;
        }
        left++;
        right--;
    }

    return true;
}

int removePalindromeSub(char* s) {
    if (s[0] == '\0') {
        return 0;
    }

    if (isPalindrome(s)) {
        return 1;
    }

    // If not a palindrome, you can remove all 'a's in one step and all 'b's in another step
    return 2;
}

int main() {
    char s1[] = "ababa";
    printf("Example 1 Output: %d\n", removePalindromeSub(s1));  // Output: 1

    char s2[] = "abb";
    printf("Example 2 Output: %d\n", removePalindromeSub(s2));  // Output: 2

    char s3[] = "baabb";
    printf("Example 3 Output: %d\n", removePalindromeSub(s3));  // Output: 2

    return 0;
}


